<?php

namespace Flarum\Release\GraphQL\OpenCollective;

enum TransactionKindEnumObject: string
{
    case ADDED_FUNDS = 'ADDED_FUNDS';
    case BALANCE_TRANSFER = 'BALANCE_TRANSFER';
    case CONTRIBUTION = 'CONTRIBUTION';
    case EXPENSE = 'EXPENSE';
    case HOST_FEE = 'HOST_FEE';
    case HOST_FEE_SHARE = 'HOST_FEE_SHARE';
    case HOST_FEE_SHARE_DEBT = 'HOST_FEE_SHARE_DEBT';
    case PAYMENT_PROCESSOR_COVER = 'PAYMENT_PROCESSOR_COVER';
    case PAYMENT_PROCESSOR_FEE = 'PAYMENT_PROCESSOR_FEE';
    case PLATFORM_FEE = 'PLATFORM_FEE';
    case PLATFORM_TIP = 'PLATFORM_TIP';
    case PLATFORM_TIP_DEBT = 'PLATFORM_TIP_DEBT';
    case PREPAID_PAYMENT_METHOD = 'PREPAID_PAYMENT_METHOD';
}
